trigger: none
pr: none

pool:
  name: Default  # Self-hosted agent

stages:
  - stage: terraform_vaildate
    displayName: terraform vaildate jobs and inti
    jobs:
    - job:
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          commandOptions: '-var-file="dev/main.tfvars"'
          backendServiceArm: 'AzureServiceConnection'
          backendAzureRmResourceGroupName: 'rg-devops'
          backendAzureRmStorageAccountName: 'wetabitterrafrom'
          backendAzureRmContainerName: 'terrafrom'
          backendAzureRmKey: 'dev-tfstate'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'validate'

  - stage: terraform_paln
    dependsOn: terraform_vaildate
    condition: succeeded('terraform_vaildate')
    displayName: terraform plan the job
    jobs:
    - job:
      steps:
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'plan'
          environmentServiceNameAzureRM: 'AzureServiceConnection'